stages:
  - prepare_environment
  - dependencies
  - build
  - upload
  # - notify
  # - deploy


prepare_environment:
  stage: prepare_environment
  script:
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG ci_prepare

dependencies:
  stage: dependencies
  script:
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG ci_dependencies
  dependencies:
    - prepare_environment

build_package:
  stage: build
  script:
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG ci_build_package
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG ci_extract_package
  artifacts:
    paths:
      - dist
    expire_in: 1 day
  dependencies:
    - dependencies

build_frontci:
  stage: build
  script:
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG ci_build_frontci
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG ci_extract_frontci
  artifacts:
    paths:
      - frontci
    expire_in: 1 day
  dependencies:
    - dependencies

upload_frontci:
  stage: upload
  dependencies:
    - build_frontci
  script:
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG FRONTCI_USER=$FRONTCI_USER FRONTCI_PASS=$FRONTCI_PASS ci_upload_frontci

notify:
  stage: notify
  script:
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG SLACKURL=$SLACKURL ci_notify
  dependencies:
    - upload


