stages:
  - prepare_environment
  - dependencies
  - build
  - deploy
  - notify
  - publish

prepare_environment:
  stage: prepare_environment
  script:
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG ci_prepare

dependencies:
  stage: dependencies
  script:
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG ci_dependencies
  dependencies:
    - prepare_environment

build_package:
  stage: build
  script:
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG ci_build_package
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG ci_extract_package
  artifacts:
    paths:
      - dist
    expire_in: 1 day
  dependencies:
    - dependencies

build_frontci:
  stage: build
  script:
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG ci_build_frontci
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG ci_extract_frontci
  artifacts:
    paths:
      - frontci
    expire_in: 1 day
  dependencies:
    - dependencies

deploy_review:
  stage: deploy
  dependencies:
    - build_frontci
  script:
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG FRONTCI_USER=$FRONTCI_USER FRONTCI_PASS=$FRONTCI_PASS ci_upload_frontci
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://front-ci.erlyvideo.ru/latest.html?p=$CI_PROJECT_NAME&r=$CI_COMMIT_REF_SLUG
  only:
    - branches
  except:
    - master

deploy_staging:
  stage: deploy
  dependencies:
    - build_frontci
  script:
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG FRONTCI_USER=$FRONTCI_USER FRONTCI_PASS=$FRONTCI_PASS ci_upload_frontci
  environment:
    name: staging
    url: http://front-ci.erlyvideo.ru/latest.html?p=$CI_PROJECT_NAME&r=$CI_COMMIT_REF_SLUG
  only:
  - master

notify:
  stage: notify
  script:
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG SLACKURL=$SLACKURL ci_notify

publish_npm:
  stage: publish
  script:
    - make -f deploy/Makefile BRANCH=$CI_COMMIT_REF_SLUG NPM_AUTH_TOKEN=$NPM_AUTH_TOKEN ci_publish_npm
  dependencies:
    - build_package
  allow_failure: true
  only:
    refs:
      - tags
